
import { GoogleGenAI } from "@google/genai";
import { EditorConfig } from "../types";
import { PASSPORT_SIZE_PROMPT } from "../constants";

export const processPassportPhoto = async (
  base64Image: string,
  mimeType: string,
  config: EditorConfig
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const prompt = `
    ${PASSPORT_SIZE_PROMPT}
    Apply the following edits to the attached person's photo:
    1. Background Removal: Remove the existing background and replace it with a solid ${config.bgColor} color.
    2. Dress Change: If requested, change the person's attire to a professional ${config.dressType}. Ensure it fits perfectly.
    3. Face Enhancement: ${config.enhanceFace ? "Slightly enhance facial features for clarity. " : ""}
    4. Skin Smoothing: ${config.smoothSkin ? "Subtly smooth the skin while maintaining natural texture. " : ""}
    5. Lighting: Set lighting to ${config.lightingAdjustment} quality. 
    Ensure the output is a clean, front-facing professional passport portrait. The person's face should be centered.
  `;

  const imagePart = {
    inlineData: {
      data: base64Image.split(',')[1], // Remove prefix if exists
      mimeType: mimeType,
    },
  };

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          imagePart
        ]
      },
    });

    let resultBase64 = '';
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        resultBase64 = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!resultBase64) {
      throw new Error("No image was generated by the model.");
    }

    return resultBase64;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
